### ISSUE TITLE
AttributeError: 'PID' object has no attribute 'starting_output'

### ISSUE THREAD

**Issue by yNosGR** [m-lundberg/simple-pid#94]
Hello, I'm trying to get simple_pid working on CircuitPython 9.2.9, but when calling the pid with starting output, it dies saying object has not attribute. Could totally be me not calling something correctly. I was hoping for some guidance.

Here's how I'm calling it:
`mypid = pid.PID(starting_output=current_output, Kp = -1, Ki = -3, Kd = -3, setpoint=33,output_limits = (3,100))`

and the console output:
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
mounting SD card                                      
Traceback (most recent call last):
  File "code.py", line 375, in <module>
AttributeError: 'PID' object has no attribute 'starting_output'   
```

**Comment by m-lundberg** [comment]
The `starting_output` argument was added in `simple-pid` version 2.0.0. Could you confirm if you are using at least this version of the library?

**Comment by yNosGR** [comment]
Looks like 2.0.1, 
```
ynosGR@laptop:/mnt/lib/simple_pid $ grep starting_output *
pid.py:        starting_output=0.0,
pid.py:        :param starting_output: The starting point for the PID's output. If you start controlling
pid.py:        self._integral = _clamp(starting_output, output_limits)
pid.pyi:        starting_output: float = ...,
ynosGR@laptop:/mnt/lib/simple_pid $ 
```

**Comment by m-lundberg** [comment]
Are you sure that your source line that you gave is line 375 in code.py? The `AttributeError` seems to indicate that you are trying to access the `starting_output` as an attribute of the pid, which doesn't exist:

```python
print(mypid.starting_output)  # Gives AttributeError
```

**Comment by yNosGR** [comment]
My bad, I had a line of code leftover from troubleshooting. It absolutely works. Sorry about that. I'll chalk it up to being tired when troubleshooting.
